import { getGitHubClient } from './client.js';
import { getRepoParams } from './client.js';
import { loadEnv } from '../config/env.js';

export async function openPullRequest(
  branchName: string,
  title: string,
  body: string,
  issueNumber: number
): Promise<string> {
  const env = loadEnv();
  const client = getGitHubClient();
  const { owner, repo } = getRepoParams();
  const { data } = await client.rest.pulls.create({
    owner,
    repo,
    title,
    body,
    head: branchName,
    base: env.REPO_DEFAULT_BRANCH,
  });
  const prUrl = data.html_url ?? data.url ?? '';
  return prUrl;
}

export function defaultPRTitle(issueNumber: number, issueTitle: string): string {
  return `feat: implement issue #${issueNumber} - ${issueTitle}`;
}

export function defaultPRBody(issueNumber: number): string {
  return `Implements #${issueNumber}\n\nGenerated by coconut-ai-worker. Please review before merging.`;
}
